LeanIt.Web/LeantIt.Web/LeantIt.Web/Controllers/BlogController.cs
using LeantIt.Web.Data;
using LeantIt.Web.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace LeantIt.Web.Controllers
{
    public class BlogController : Controller
    {

        private readonly ILogger<HomeController> _logger;
        private readonly UserManager<AplicacaoUser> _userManager;
        private readonly SignInManager<AplicacaoUser> _signInManager;
        private AppDbContext _context;

        public BlogController(ILogger<HomeController> logger, AppDbContext context, SignInManager<AplicacaoUser> signInManager, UserManager<AplicacaoUser> userManager)
        {
            _logger = logger;
            _context = context;
            _signInManager = signInManager;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            //Verifica se o usuário está autenticado
            if (User.Identity.IsAuthenticated)
            {
                //Pega o id do usuário que está logado
                var idParaEncontrar = _signInManager.UserManager.GetUserId(User);

                //Verifica se existe o id do usuário logado no banco
                var usuarioComNomeDeExibicao = _userManager.Users.FirstOrDefault(x => x.Id == idParaEncontrar);

                //Se encontrar o id do usuário logado no banco a variável usuarioComNomeDeExibicao vai ter um valor, ou seja, ela não será nula, então ela vai para o if
                if (usuarioComNomeDeExibicao != null)
                {
                    //Pega o nome do usuário logado e armazenamos em uma ViewBag, para poder usar no front
                    ViewBag.User = usuarioComNomeDeExibicao.Nome;
                }

                //Armazena na variável o name do usuário autenticado
                var user = User.Identity.Name;

                //Verifica se no banco possui o name do usuário autenticado, se tiver vai armazena na variável o registro do usuário
                var users = _signInManager.UserManager.Users.FirstOrDefault(userItem => userItem.UserName == user);

                //Verifica se o usuário que tá logado possui alguma pendência de aluguel na tabela AluguelCarros
                var pendente = _context.AlguelCarros.FirstOrDefault(aluguelSelecionado => aluguelSelecionado.User == users.Id && aluguelSelecionado.Pendente == true);

                //Armazena o registro da verificação acima, está em uma ViewBag  para poder usar no front
                ViewBag.Pendente = pendente;
            }

            return View();
        }
    }
}

LeanIt.Web/LeantIt.Web/LeantIt.Web/Controllers/CarrosController.cs
using LeantIt.Web.Data;
using LeantIt.Web.Models;
using LeantIt.Web.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using X.PagedList;

namespace LeantIt.Web.Controllers;

// ************************************************ //
// CONTROLADOR DAS ALTERAÇÕES E INSERÇÃO DE CARROS  //
// ************************************************ //
public class CarrosController : Controller
{
    private readonly ILogger<CarrosController> _logger;
    private readonly UserManager<AplicacaoUser> _userManager;
    private readonly SignInManager<AplicacaoUser> _signInManager;
    private AppDbContext _context; // este é o DbContext (contexto da base de dados usada no nosso projeto)
                                   // em todas os casos de tratamentos de dados, utilize "_context" para acessar as tabelas...

    // construtor do controller, aqui, devem ser assinadas todas as injeções de dependencias
    public CarrosController(ILogger<CarrosController> logger, AppDbContext context, SignInManager<AplicacaoUser> signInManager, UserManager<AplicacaoUser> userManager)
    {
        _logger = logger;
        _context = context;
        _signInManager = signInManager;
        _userManager = userManager;
    }

    // Aqui a view retorna a página de adicionar
    [HttpGet]
    [Authorize(Roles ="Admin")]
    public IActionResult Adicionar()
    {
        var categorias = _context.Categorias.ToList();

        var adicionarCarroViewModel = new AdicionarCarroViewModel()
        {
            Categoria = categorias.Select(x => new SelectListItem { Text = x.Descricao, Value = x.Id.ToString() })
        };
        if (User.Identity.IsAuthenticated)
        {
            var idParaEncontrar = _signInManager.UserManager.GetUserId(User);
            var usuarioComNomeDeExibicao = _userManager.Users.FirstOrDefault(x => x.Id == idParaEncontrar);
            if (usuarioComNomeDeExibicao != null)
            {
                ViewBag.User = usuarioComNomeDeExibicao.Nome;
            }

            var user = User.Identity.Name;
            var users = _signInManager.UserManager.Users.FirstOrDefault(userItem => userItem.UserName == user);

            var pendente = _context.AlguelCarros.FirstOrDefault(aluguelSelecionado => aluguelSelecionado.User == users.Id && aluguelSelecionado.Pendente == true);
            ViewBag.Pendente = pendente;
        }
        return View(adicionarCarroViewModel);
    }

    // Aqui a view envia os dados da página "Adicionar"
    [HttpPost]
    public IActionResult Adicionar(AdicionarCarroViewModel adicionarCarroViewModel)
    {
        var idCategoria = Guid.Parse(adicionarCarroViewModel.CategoriaSelecionada);
        var selecionado = _context.Categorias.FirstOrDefault(x => x.Id == idCategoria);

        if (adicionarCarroViewModel != null)
        {
            var carro = new CarroModel()
            {
                Descricao = adicionarCarroViewModel.Descricao,
                Marca = adicionarCarroViewModel.Marca,
                Modelo = adicionarCarroViewModel.Modelo,
                Year = adicionarCarroViewModel.Year,
                Placa = adicionarCarroViewModel.Placa,
                Cor = adicionarCarroViewModel.Cor,
                UrlImagem = "none",
                Latitude = adicionarCarroViewModel.Latitude,
                Categoria = selecionado,
                Longitude = adicionarCarroViewModel.Longitude,
                Status = adicionarCarroViewModel.Status
            };

            _context.Carros.Add(carro);
            _context.SaveChanges();

            return RedirectToAction("Index", "Home");

        }

        return View(null);
    }

    // Aqui a view retorna os dados para a pagina
    [HttpGet]
    [Authorize(Roles = "Admin")]
    public IActionResult Listar(string sortOrder, int? page)
    {
        
        var carros = _context.Carros; // retorna os registros da tabela de carros do banco de dados
        int pageSize = 5; // Quantidade de itens que aparecerão por página
        int pageNumber = (page ?? 1); // Referência de qual página o usuário está no momento

        // SE FOR "Nome Crescente", ELE IRÁ CAIR NO case "nome_desc"
        // SE FOR "Nome Decrescente", ELE IRÁ CAIR NO case "nome_asc"
        // O VALOR DEFAULT É APENAS A LISTA DE CARROS NORMAL ASSIM COMO ESTÁ REGISTRADO NAS TABELAS
        if (User.Identity.IsAuthenticated)
        {
            var idParaEncontrar = _signInManager.UserManager.GetUserId(User);
            var usuarioComNomeDeExibicao = _userManager.Users.FirstOrDefault(x => x.Id == idParaEncontrar);
            if (usuarioComNomeDeExibicao != null)
            {
                ViewBag.User = usuarioComNomeDeExibicao.Nome;
            }
            var user = User.Identity.Name;
            var users = _signInManager.UserManager.Users.FirstOrDefault(userItem => userItem.UserName == user);

            var pendente = _context.AlguelCarros.FirstOrDefault(aluguelSelecionado => aluguelSelecionado.User == users.Id && aluguelSelecionado.Pendente == true);
            ViewBag.Pendente = pendente;
        }
        switch (sortOrder)
        {
            case "nome_desc":
                var descOrder = carros.OrderByDescending(s => s.Marca);
                return View(descOrder.ToPagedList(pageNumber, pageSize));
            case "nome_asc":
                var ascOrder = carros.OrderBy(s => s.Marca);
                return View(ascOrder.ToPagedList(pageNumber, pageSize));
            default:
                var normalOrder = carros.OrderByDescending(s => s.Marca);
                return View(normalOrder.ToPagedList(pageNumber, pageSize));
        }
        
    }


    // Aqui a view retorna os dados para uma simples pagina de deletar o carro
    [HttpGet]
    [Authorize(Roles ="Admin")]
    public IActionResult Remover(Guid? id)
    {
        var carros = _context.Carros.ToList();

        if (User.Identity.IsAuthenticated)
        {
            var idParaEncontrar = _signInManager.UserManager.GetUserId(User);
            var usuarioComNomeDeExibicao = _userManager.Users.FirstOrDefault(x => x.Id == idParaEncontrar);
            if (usuarioComNomeDeExibicao != null)
            {
                ViewBag.User = usuarioComNomeDeExibicao.Nome;
            }

            var user = User.Identity.Name;
            var users = _signInManager.UserManager.Users.FirstOrDefault(userItem => userItem.UserName == user);

            var pendente = _context.AlguelCarros.FirstOrDefault(aluguelSelecionado => aluguelSelecionado.User == users.Id && aluguelSelecionado.Pendente == true);
            ViewBag.Pendente = pendente;
        }

        foreach (var carro in carros)
        {
            if (id == carro.Id)
            {
                return View(carro);
            }
        }

        return RedirectToAction("Listar");
    }

    // Aqui a view efetivamente deleta o carro 
    [HttpPost]
    public IActionResult Remover(CarroModel carro)
    {
        var carros = _context.Carros.ToList();

        foreach (var carroItem in carros)
        {
            if (carroItem.Id == carro.Id)
            {
                _context.Carros.Remove(carroItem);
                _context.SaveChanges();
            }
        }

        return RedirectToAction("Listar");
    }

    // Aqui a view retorna os dados para fazer a edição de um carro, trazendo todos os dados do carro existente
    [HttpGet]
    [Authorize(Roles = "Admin")]
    public IActionResult Editar(Guid id)
    {
        var carroDoBancoDeDados = _context.Carros.Include(x => x.Categoria).FirstOrDefault(x => x.Id == id);

        var categoriaSelecionada = _context.Categorias.FirstOrDefault(x => x.Id == carroDoBancoDeDados.Categoria.Id);

        var categorias = _context.Categorias.ToList();

        var novoModel = new EditarCarroViewModel()
        {
            Id = carroDoBancoDeDados.Id,
            Descricao = carroDoBancoDeDados.Descricao,
            Marca = carroDoBancoDeDados.Marca,
            Modelo = carroDoBancoDeDados.Modelo,
            Year = carroDoBancoDeDados.Year,
            Placa = carroDoBancoDeDados.Placa,
            Cor = carroDoBancoDeDados.Cor,
            UrlImagem = "none",
            Latitude = carroDoBancoDeDados.Latitude,
            Longitude = carroDoBancoDeDados.Longitude,
            Categoria = categorias.Select(x => new SelectListItem { Text = x.Descricao, Value = x.Id.ToString() }),
            CategoriaSelecionada = categoriaSelecionada.Id.ToString(),
            Status = carroDoBancoDeDados.Status
        };

        if (User.Identity.IsAuthenticated)
        {
            var idParaEncontrar = _signInManager.UserManager.GetUserId(User);
            var usuarioComNomeDeExibicao = _userManager.Users.FirstOrDefault(x => x.Id == idParaEncontrar);
            if (usuarioComNomeDeExibicao != null)
            {
                ViewBag.User = usuarioComNomeDeExibicao.Nome;
            }
            var user = User.Identity.Name;
            var users = _signInManager.UserManager.Users.FirstOrDefault(userItem => userItem.UserName == user);

            var pendente = _context.AlguelCarros.FirstOrDefault(aluguelSelecionado => aluguelSelecionado.User == users.Id && aluguelSelecionado.Pendente == true);
            ViewBag.Pendente = pendente;
        }


        return View(novoModel);
    }

    // Aqui a view envia os dados atualizados e efetua uma atualização nas colunas
    [HttpPost]
    public IActionResult Editar(EditarCarroViewModel editarCarroViewModel)
    {
        var carroAntigo = _context.Carros.FirstOrDefault(x => x.Id == editarCarroViewModel.Id);

        var idCategoria = Guid.Parse(editarCarroViewModel.CategoriaSelecionada);

        var selecionado = _context.Categorias.FirstOrDefault(x => x.Id == idCategoria);

        if (carroAntigo != null)
        {

LeanIt.Web/LeantIt.Web/LeantIt.Web/Controllers/DashboardController.cs
using LeantIt.Web.Data;
using LeantIt.Web.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LeantIt.Web.Controllers
{
    public class DashboardController : Controller
    {
        private readonly AppDbContext _context;
        private readonly SignInManager<AplicacaoUser> _signInManager;
        private readonly UserManager<AplicacaoUser> _userManager;

        public DashboardController(AppDbContext context, SignInManager<AplicacaoUser> signInManager, UserManager<AplicacaoUser> userManager)
        {
            _context = context;
            _signInManager = signInManager;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            //Verifica se o usuário está autenticado
            if (User.Identity.IsAuthenticated)
            {
                //Pega o id do usuário que está logado
                var idParaEncontrar = _signInManager.UserManager.GetUserId(User);

                //Verifica se existe o id do usuário logado no banco
                var usuarioComNomeDeExibicao = _userManager.Users.FirstOrDefault(x => x.Id == idParaEncontrar);

                //Se encontrar o id do usuário logado no banco a variável usuarioComNomeDeExibicao vai ter um valor, ou seja, ela não será nula, então ela vai para o if
                if (usuarioComNomeDeExibicao != null)
                {
                    //Pega o nome do usuário logado e armazenamos em uma ViewBag, para poder usar no front
                    ViewBag.User = usuarioComNomeDeExibicao.Nome;
                }

                //Armazena na variável o name do usuário autenticado
                var user = User.Identity.Name;

                //Verifica se no banco possui o name do usuário autenticado, se tiver vai armazena na variável o registro do usuário
                var users = _signInManager.UserManager.Users.FirstOrDefault(userItem => userItem.UserName == user);

                //Verifica se o usuário que tá logado possui alguma pendência de aluguel na tabela AluguelCarros
                var pendente = _context.AlguelCarros.FirstOrDefault(aluguelSelecionado => aluguelSelecionado.User == users.Id && aluguelSelecionado.Pendente == true);

                //Armazena o registro da verificação acima, está em uma ViewBag  para poder usar no front
                ViewBag.Pendente = pendente;
            }

            //Armazena na variável o registro da categoria Basico
            var categoriaBasico = _context.Categorias.FirstOrDefault(categoriaCarro => categoriaCarro.Descricao == "Basico");

            //Armazena na variável a QUANTIDADE de carros que foram alugados da categoria Basico
            var carroBasico = _context.AlguelCarros.Where(aluguelCarro => aluguelCarro.Carro.Categoria.Descricao == categoriaBasico.Descricao).Count();

            //Armazena na ViewBag o valor da variável acima, está em uma ViewBag para poder usar no front
            ViewBag.CarroBasico = carroBasico;

            //Armazena na variável o registro da categoria Familia
            var categoriaFamilias = _context.Categorias.FirstOrDefault(categoriaF => categoriaF.Descricao == "Familia");

            //Armazena na variável a QUANTIDADE de carros que foram alugados da categoria Familia
            var carroFamilia = _context.AlguelCarros.Where(carroF => carroF.Carro.Categoria.Descricao == categoriaFamilias.Descricao).Count();

            //Armazena na ViewBag o valor da variável acima, está em uma ViewBag para poder usar no front
            ViewBag.CarroFamilia = carroFamilia;

            //Armazena na variável o registro da categoria Carga
            var categoriaCarga = _context.Categorias.FirstOrDefault(categoriaC => categoriaC.Descricao == "Carga");

            //Armazena na variável a QUANTIDADE de carros que foram alugados da categoria Carga
            var carroCarga = _context.AlguelCarros.Where(carroC => carroC.Carro.Categoria.Descricao == categoriaCarga.Descricao).Count();

            //Armazena na ViewBag o valor da variável acima, está em uma ViewBag para poder usar no front
            ViewBag.CarroCarga = carroCarga;



            //
            var carroAtivo = _context.Carros.Where(carroA => carroA.Status == true).Count();
            ViewBag.CarroAtivo = carroAtivo;

            var carroInativo = _context.Carros.Where(carroI => carroI.Status == false).Count();
            ViewBag.CarroInativo = carroInativo;



            var qCarrosBasico = _context.Carros.Where(QCarro => QCarro.Categoria.Descricao == "Basico").Count();
            ViewBag.QCarroBasico = qCarrosBasico;

            var qCarrosFamilia = _context.Carros.Where(QCarro => QCarro.Categoria.Descricao == "Familia").Count();
            ViewBag.QCarroFamilia = qCarrosFamilia;

            var qCarrosCarga = _context.Carros.Where(QCarro => QCarro.Categoria.Descricao == "Carga").Count();
            ViewBag.QCarroCarga = qCarrosCarga;

            return View();
        }
    }
}

LeanIt.Web/LeantIt.Web/LeantIt.Web/Views/Dashboard/Index.cshtml
@{
    ViewData["Title"] = "Dasboards";

}
<header>
    <a><img src="https://res.cloudinary.com/dtvypcack/image/upload/v1701711075/logo_recorte_dxihjz.png" class="logo"></a>

    <nav class="navbar-desktop">
        <ul>
            <li><a asp-action="Index" asp-area="" asp-controller="Home" >Home</a></li>
            <li><a asp-area="" asp-controller="OurServices" asp-action="Index">Categorias</a></li>
            @if (User.IsInRole("Admin"))
            {
                <li class="nav-item dropdown">
                    <a href="#" style="color:#ff8110">Admin</a>
                    <ul class="dropdown-menu">
                        <li><a class="add" asp-area="" asp-controller="Carros" asp-action="Adicionar">Add Carro</a></li>
                        <li><a class="listando" asp-area="" asp-controller="Carros" asp-action="Listar">Listar Carros</a></li>
                        <li>
                            <a class="add" id="register" asp-area="Identity" asp-page="/Account/Register">Registrar</a>
                        </li>
                        <li><a class="dash, listando" asp-area="" asp-action="Index" asp-controller="Dashboard">Dash</a></li>
                        <li><a class="add" asp-area="" asp-action="AdicionarMP" asp-controller="ChatBot">Add ChatBot</a></li>
                        <li><a class="listando" asp-area="" asp-action="Index" asp-controller="ChatBot">Listar ChatBot</a></li>
                    </ul>
                </li>
            }
            <partial name="_LoginPartial" />
    </nav>
</header>
<div>
    <h2>Quantidades de Carros por Categoria</h2>
    <div style="margin-bottom: 10%; max-height:30%; display:flex; justify-content:center">
        <canvas id="myChart" ></canvas>
    </div>
    <h2>Carros Ativo/Inativo</h2>
    <div style="margin-bottom: 10%; max-height:30%; display:flex; justify-content:center">

        <canvas id="myChart2"></canvas>
    </div>
    <h2>Carros Usados por Categoria</h2>
    <div style="margin-bottom: 10%; max-height:30%; display:flex; justify-content:center">
        <canvas id="myChart3" ></canvas>
    </div>
</div>

<footer>

    <div class="footer-main">
        <div class="footer-about">
            <p class="footer-title">Sobre a LeanIt</p>
            <p class="footer-paragraph-about">Nós levamos a outro nível a locomoção por meio de nossa tecnologia</p>
            <div class="icons-about"><a href="#"><i class="fa-brands fa-youtube"></a></i> <a href="https://pt-br.facebook.com/"><i class="fa-brands fa-facebook"></a></i> <a href="https://www.instagram.com/_leanit?igsh=M2R2amd0ejFyeWky"><i class="fa-brands fa-instagram"></i></a> <a href="https://twitter.com/"><i class="fa-brands fa-square-x-twitter"></i></a></div>
        </div>

        <div class="footer-extra">
            <p class="footer-title">Nossa Página</p>
            <p>@Html.ActionLink("Nosso blog", "Index", "Blog")</p>
            <p><a href="https://www.entra21.com.br/" target="_blank">Entra21</a></p>
            <p>@Html.ActionLink("Guia Turístico", "Index", "Turismo")</p>
            <p>@Html.ActionLink("Termos de Uso", "Index", "Termos")</p>
        </div>

        <div class="footer-contact">
            <p class="footer-title">Contate-nos</p>
            <p class="paragraph-contact paragraph-contact-top"><i class="fa-solid fa-phone phone-icon"></i>+55 (47) 9999-9999</p>
            <p class="paragraph-contact"><i class="fa-solid fa-envelope email-icon"></i><a href="#">contact@leanit.com</a></p>
        </div>
    </div>

    <p class="footer-copyright">Copyright © 2023 All rights deserved</p>

</footer>


@section Styles{
    <link rel="stylesheet" href="~/css/dash.css" />
}

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
    const ctx = document.getElementById('myChart');
    new Chart(ctx, {
        type: 'bar',
        data: {
            labels: ['Carro Básico', 'Carro Família', 'Carro Carga'],
            datasets: [{
                label: 'Quantidades de Carros por Categoria',
                data: [@ViewBag.QCarroBasico, @ViewBag.QCarroFamilia, @ViewBag.QCarroCarga],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });


    const ctx2 = document.getElementById('myChart2');
    new Chart(ctx2, {
        type: 'doughnut',
        data:{
        
            labels: [
                'Ativo',
                'Inativo',
            ],
            datasets: [{
                label: 'Carros Ativo/Inativo',
                data: [@ViewBag.CarroAtivo, @ViewBag.CarroInativo],
                backgroundColor: [
                    'rgb(255, 99, 132)',
                    'rgb(54, 162, 235)'
                ],
                hoverOffset: 4
            }]
        }
    });


    const ctx3 = document.getElementById('myChart3');
    new Chart(ctx3, {
        type: 'bar',
        data: {
            labels: [
                'Carro Básico',
                'Carro Família',
                'Carro Carga'
            ],
            datasets: [{
                label: 'Carros Usados por Categoria',
                data: [@ViewBag.CarroBasico, @ViewBag.CarroFamilia, @ViewBag.CarroCarga],
                backgroundColor: [
                    'rgb(255, 99, 132)',
                    'rgb(75, 192, 192)',
                    'rgb(255, 205, 86)',
                ]
            }]
        }
    });
</script>