LeanIt.Web/LeantIt.Web/LeantIt.Web/Controllers/BlogController.cs
using LeantIt.Web.Data;
using LeantIt.Web.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace LeantIt.Web.Controllers
{
    public class BlogController : Controller
    {

        private readonly ILogger<HomeController> _logger;
        private readonly UserManager<AplicacaoUser> _userManager;
        private readonly SignInManager<AplicacaoUser> _signInManager;
        private AppDbContext _context;

        public BlogController(ILogger<HomeController> logger, AppDbContext context, SignInManager<AplicacaoUser> signInManager, UserManager<AplicacaoUser> userManager)
        {
            _logger = logger;
            _context = context;
            _signInManager = signInManager;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            //Verifica se o usuário está autenticado
            if (User.Identity.IsAuthenticated)
            {
                //Pega o id do usuário que está logado
                var idParaEncontrar = _signInManager.UserManager.GetUserId(User);

                //Verifica se existe o id do usuário logado no banco
                var usuarioComNomeDeExibicao = _userManager.Users.FirstOrDefault(x => x.Id == idParaEncontrar);

                //Se encontrar o id do usuário logado no banco a variável usuarioComNomeDeExibicao vai ter um valor, ou seja, ela não será nula, então ela vai para o if
                if (usuarioComNomeDeExibicao != null)
                {
                    //Pega o nome do usuário logado e armazenamos em uma ViewBag, para poder usar no front
                    ViewBag.User = usuarioComNomeDeExibicao.Nome;
                }

                //Armazena na variável o name do usuário autenticado
                var user = User.Identity.Name;

                //Verifica se no banco possui o name do usuário autenticado, se tiver vai armazena na variável o registro do usuário
                var users = _signInManager.UserManager.Users.FirstOrDefault(userItem => userItem.UserName == user);

                //Verifica se o usuário que tá logado possui alguma pendência de aluguel na tabela AluguelCarros
                var pendente = _context.AlguelCarros.FirstOrDefault(aluguelSelecionado => aluguelSelecionado.User == users.Id && aluguelSelecionado.Pendente == true);

                //Armazena o registro da verificação acima, está em uma ViewBag  para poder usar no front
                ViewBag.Pendente = pendente;
            }

            return View();
        }
    }
}

LeanIt.Web/LeantIt.Web/LeantIt.Web/Controllers/CarrosController.cs
using LeantIt.Web.Data;
using LeantIt.Web.Models;
using LeantIt.Web.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using X.PagedList;

namespace LeantIt.Web.Controllers;

// ************************************************ //
// CONTROLADOR DAS ALTERAÇÕES E INSERÇÃO DE CARROS  //
// ************************************************ //
public class CarrosController : Controller
{
    private readonly ILogger<CarrosController> _logger;
    private readonly UserManager<AplicacaoUser> _userManager;
    private readonly SignInManager<AplicacaoUser> _signInManager;
    private AppDbContext _context; // este é o DbContext (contexto da base de dados usada no nosso projeto)
                                   // em todas os casos de tratamentos de dados, utilize "_context" para acessar as tabelas...

    // construtor do controller, aqui, devem ser assinadas todas as injeções de dependencias
    public CarrosController(ILogger<CarrosController> logger, AppDbContext context, SignInManager<AplicacaoUser> signInManager, UserManager<AplicacaoUser> userManager)
    {
        _logger = logger;
        _context = context;
        _signInManager = signInManager;
        _userManager = userManager;
    }

    // Aqui a view retorna a página de adicionar
    [HttpGet]
    [Authorize(Roles ="Admin")]
    public IActionResult Adicionar()
    {
        var categorias = _context.Categorias.ToList();

        var adicionarCarroViewModel = new AdicionarCarroViewModel()
        {
            Categoria = categorias.Select(x => new SelectListItem { Text = x.Descricao, Value = x.Id.ToString() })
        };
        if (User.Identity.IsAuthenticated)
        {
            var idParaEncontrar = _signInManager.UserManager.GetUserId(User);
            var usuarioComNomeDeExibicao = _userManager.Users.FirstOrDefault(x => x.Id == idParaEncontrar);
            if (usuarioComNomeDeExibicao != null)
            {
                ViewBag.User = usuarioComNomeDeExibicao.Nome;
            }

            var user = User.Identity.Name;
            var users = _signInManager.UserManager.Users.FirstOrDefault(userItem => userItem.UserName == user);

            var pendente = _context.AlguelCarros.FirstOrDefault(aluguelSelecionado => aluguelSelecionado.User == users.Id && aluguelSelecionado.Pendente == true);
            ViewBag.Pendente = pendente;
        }
        return View(adicionarCarroViewModel);
    }

    // Aqui a view envia os dados da página "Adicionar"
    [HttpPost]
    public IActionResult Adicionar(AdicionarCarroViewModel adicionarCarroViewModel)
    {
        var idCategoria = Guid.Parse(adicionarCarroViewModel.CategoriaSelecionada);
        var selecionado = _context.Categorias.FirstOrDefault(x => x.Id == idCategoria);

        if (adicionarCarroViewModel != null)
        {
            var carro = new CarroModel()
            {
                Descricao = adicionarCarroViewModel.Descricao,
                Marca = adicionarCarroViewModel.Marca,
                Modelo = adicionarCarroViewModel.Modelo,
                Year = adicionarCarroViewModel.Year,
                Placa = adicionarCarroViewModel.Placa,
                Cor = adicionarCarroViewModel.Cor,
                UrlImagem = "none",
                Latitude = adicionarCarroViewModel.Latitude,
                Categoria = selecionado,
                Longitude = adicionarCarroViewModel.Longitude,
                Status = adicionarCarroViewModel.Status
            };

            _context.Carros.Add(carro);
            _context.SaveChanges();

            return RedirectToAction("Index", "Home");

        }

        return View(null);
    }

    // Aqui a view retorna os dados para a pagina
    [HttpGet]
    [Authorize(Roles = "Admin")]
    public IActionResult Listar(string sortOrder, int? page)
    {
        
        var carros = _context.Carros; // retorna os registros da tabela de carros do banco de dados
        int pageSize = 5; // Quantidade de itens que aparecerão por página
        int pageNumber = (page ?? 1); // Referência de qual página o usuário está no momento

        // SE FOR "Nome Crescente", ELE IRÁ CAIR NO case "nome_desc"
        // SE FOR "Nome Decrescente", ELE IRÁ CAIR NO case "nome_asc"
        // O VALOR DEFAULT É APENAS A LISTA DE CARROS NORMAL ASSIM COMO ESTÁ REGISTRADO NAS TABELAS
        if (User.Identity.IsAuthenticated)
        {
            var idParaEncontrar = _signInManager.UserManager.GetUserId(User);
            var usuarioComNomeDeExibicao = _userManager.Users.FirstOrDefault(x => x.Id == idParaEncontrar);
            if (usuarioComNomeDeExibicao != null)
            {
                ViewBag.User = usuarioComNomeDeExibicao.Nome;
            }
            var user = User.Identity.Name;
            var users = _signInManager.UserManager.Users.FirstOrDefault(userItem => userItem.UserName == user);

            var pendente = _context.AlguelCarros.FirstOrDefault(aluguelSelecionado => aluguelSelecionado.User == users.Id && aluguelSelecionado.Pendente == true);
            ViewBag.Pendente = pendente;
        }
        switch (sortOrder)
        {
            case "nome_desc":
                var descOrder = carros.OrderByDescending(s => s.Marca);
                return View(descOrder.ToPagedList(pageNumber, pageSize));
            case "nome_asc":
                var ascOrder = carros.OrderBy(s => s.Marca);
                return View(ascOrder.ToPagedList(pageNumber, pageSize));
            default:
                var normalOrder = carros.OrderByDescending(s => s.Marca);
                return View(normalOrder.ToPagedList(pageNumber, pageSize));
        }
        
    }


    // Aqui a view retorna os dados para uma simples pagina de deletar o carro
    [HttpGet]
    [Authorize(Roles ="Admin")]
    public IActionResult Remover(Guid? id)
    {
        var carros = _context.Carros.ToList();

        if (User.Identity.IsAuthenticated)
        {
            var idParaEncontrar = _signInManager.UserManager.GetUserId(User);
            var usuarioComNomeDeExibicao = _userManager.Users.FirstOrDefault(x => x.Id == idParaEncontrar);
            if (usuarioComNomeDeExibicao != null)
            {
                ViewBag.User = usuarioComNomeDeExibicao.Nome;
            }

            var user = User.Identity.Name;
            var users = _signInManager.UserManager.Users.FirstOrDefault(userItem => userItem.UserName == user);

            var pendente = _context.AlguelCarros.FirstOrDefault(aluguelSelecionado => aluguelSelecionado.User == users.Id && aluguelSelecionado.Pendente == true);
            ViewBag.Pendente = pendente;
        }

        foreach (var carro in carros)
        {
            if (id == carro.Id)
            {
                return View(carro);
            }
        }

        return RedirectToAction("Listar");
    }

    // Aqui a view efetivamente deleta o carro 
    [HttpPost]
    public IActionResult Remover(CarroModel carro)
    {
        var carros = _context.Carros.ToList();

        foreach (var carroItem in carros)
        {
            if (carroItem.Id == carro.Id)
            {
                _context.Carros.Remove(carroItem);
                _context.SaveChanges();
            }
        }

        return RedirectToAction("Listar");
    }

    // Aqui a view retorna os dados para fazer a edição de um carro, trazendo todos os dados do carro existente
    [HttpGet]
    [Authorize(Roles = "Admin")]
    public IActionResult Editar(Guid id)
    {
        var carroDoBancoDeDados = _context.Carros.Include(x => x.Categoria).FirstOrDefault(x => x.Id == id);

        var categoriaSelecionada = _context.Categorias.FirstOrDefault(x => x.Id == carroDoBancoDeDados.Categoria.Id);

        var categorias = _context.Categorias.ToList();

        var novoModel = new EditarCarroViewModel()
        {
            Id = carroDoBancoDeDados.Id,
            Descricao = carroDoBancoDeDados.Descricao,
            Marca = carroDoBancoDeDados.Marca,
            Modelo = carroDoBancoDeDados.Modelo,
            Year = carroDoBancoDeDados.Year,
            Placa = carroDoBancoDeDados.Placa,
            Cor = carroDoBancoDeDados.Cor,
            UrlImagem = "none",
            Latitude = carroDoBancoDeDados.Latitude,
            Longitude = carroDoBancoDeDados.Longitude,
            Categoria = categorias.Select(x => new SelectListItem { Text = x.Descricao, Value = x.Id.ToString() }),
            CategoriaSelecionada = categoriaSelecionada.Id.ToString(),
            Status = carroDoBancoDeDados.Status
        };

        if (User.Identity.IsAuthenticated)
        {
            var idParaEncontrar = _signInManager.UserManager.GetUserId(User);
            var usuarioComNomeDeExibicao = _userManager.Users.FirstOrDefault(x => x.Id == idParaEncontrar);
            if (usuarioComNomeDeExibicao != null)
            {
                ViewBag.User = usuarioComNomeDeExibicao.Nome;
            }
            var user = User.Identity.Name;
            var users = _signInManager.UserManager.Users.FirstOrDefault(userItem => userItem.UserName == user);

            var pendente = _context.AlguelCarros.FirstOrDefault(aluguelSelecionado => aluguelSelecionado.User == users.Id && aluguelSelecionado.Pendente == true);
            ViewBag.Pendente = pendente;
        }


        return View(novoModel);
    }

    // Aqui a view envia os dados atualizados e efetua uma atualização nas colunas
    [HttpPost]
    public IActionResult Editar(EditarCarroViewModel editarCarroViewModel)
    {
        var carroAntigo = _context.Carros.FirstOrDefault(x => x.Id == editarCarroViewModel.Id);

        var idCategoria = Guid.Parse(editarCarroViewModel.CategoriaSelecionada);

        var selecionado = _context.Categorias.FirstOrDefault(x => x.Id == idCategoria);

        if (carroAntigo != null)
        {

LeanIt.Web/LeantIt.Web/LeantIt.Web/Controllers/TermosController.cs
using LeantIt.Web.Data;
using LeantIt.Web.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LeantIt.Web.Controllers
{
    public class TermosController : Controller
    {
        private readonly ILogger<TermosController> _logger;
        private readonly SignInManager<AplicacaoUser> _signInManager;
        private readonly UserManager<AplicacaoUser> _userManager;
        private AppDbContext _context;

        public TermosController(ILogger<TermosController> logger, AppDbContext context, SignInManager<AplicacaoUser> signInManager, UserManager<AplicacaoUser> userManager)
        {
            _logger = logger;
            _context = context;
            _signInManager = signInManager;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            //Verifica se o usuário está autenticado
            if (User.Identity.IsAuthenticated)
            {
                //Pega o id do usuário que está logado
                var idParaEncontrar = _signInManager.UserManager.GetUserId(User);

                //Verifica se existe o id do usuário logado no banco
                var usuarioComNomeDeExibicao = _userManager.Users.FirstOrDefault(x => x.Id == idParaEncontrar);

                //Se encontrar o id do usuário logado no banco a variável usuarioComNomeDeExibicao vai ter um valor, ou seja, ela não será nula, então ela vai para o if
                if (usuarioComNomeDeExibicao != null)
                {
                    //Pega o nome do usuário logado e armazenamos em uma ViewBag, para poder usar no front
                    ViewBag.User = usuarioComNomeDeExibicao.Nome;
                }

                //Armazena na variável o name do usuário autenticado
                var user = User.Identity.Name;

                //Verifica se no banco possui o name do usuário autenticado, se tiver vai armazena na variável o registro do usuário
                var users = _signInManager.UserManager.Users.FirstOrDefault(userItem => userItem.UserName == user);

                //Verifica se o usuário que tá logado possui alguma pendência de aluguel na tabela AluguelCarros
                var pendente = _context.AlguelCarros.FirstOrDefault(aluguelSelecionado => aluguelSelecionado.User == users.Id && aluguelSelecionado.Pendente == true);

                //Armazena o registro da verificação acima, está em uma ViewBag  para poder usar no front
                ViewBag.Pendente = pendente;
            }
            return View();
        }
    }
}

LeanIt.Web/LeantIt.Web/LeantIt.Web/Controllers/TurismoController.cs
using LeantIt.Web.Data;
using LeantIt.Web.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LeantIt.Web.Controllers
{
    public class TurismoController : Controller
    {
        private readonly ILogger<TurismoController> _logger;
        private readonly SignInManager<AplicacaoUser> _signInManager;
        private readonly UserManager<AplicacaoUser> _userManager;
        private AppDbContext _context;

        public TurismoController(ILogger<TurismoController> logger, AppDbContext context, SignInManager<AplicacaoUser> signInManager, UserManager<AplicacaoUser> userManager)
        {
            _logger = logger;
            _context = context;
            _signInManager = signInManager;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            //Verifica se o usuário está autenticado
            if (User.Identity.IsAuthenticated)
            {
                //Pega o id do usuário que está logado
                var idParaEncontrar = _signInManager.UserManager.GetUserId(User);

                //Verifica se existe o id do usuário logado no banco
                var usuarioComNomeDeExibicao = _userManager.Users.FirstOrDefault(x => x.Id == idParaEncontrar);

                //Se encontrar o id do usuário logado no banco a variável usuarioComNomeDeExibicao vai ter um valor, ou seja, ela não será nula, então ela vai para o if
                if (usuarioComNomeDeExibicao != null)
                {
                    //Pega o nome do usuário logado e armazenamos em uma ViewBag, para poder usar no front
                    ViewBag.User = usuarioComNomeDeExibicao.Nome;
                }

                //Armazena na variável o name do usuário autenticado
                var user = User.Identity.Name;

                //Verifica se no banco possui o name do usuário autenticado, se tiver vai armazena na variável o registro do usuário
                var users = _signInManager.UserManager.Users.FirstOrDefault(userItem => userItem.UserName == user);

                //Verifica se o usuário que tá logado possui alguma pendência de aluguel na tabela AluguelCarros
                var pendente = _context.AlguelCarros.FirstOrDefault(aluguelSelecionado => aluguelSelecionado.User == users.Id && aluguelSelecionado.Pendente == true);
                
                //Armazena o registro da verificação acima, está em uma ViewBag  para poder usar no front
                ViewBag.Pendente = pendente;
            }
            return View();
        }
    }
}

LeanIt.Web/LeantIt.Web/LeantIt.Web/Views/Turismo/Index.cshtml
@using Microsoft.AspNetCore.Identity
@model List<LeantIt.Web.Models.CarroModel>
@inject SignInManager<AplicacaoUser> SignInManager
@inject UserManager<AplicacaoUser> UserManager

@{
    ViewData["Title"] = "Guia Turístico - LeanIt";
}
<header>
    <nav class="mobile-nav">
        <div>
            <a asp-area="" asp-controller="Home" asp-action="Index"><img src="https://res.cloudinary.com/dtvypcack/image/upload/v1701711075/logo_recorte_dxihjz.png" class="logo-mobile" style="cursor: pointer;" /></a>
        </div>
        <div style="display: flex; flex-direction: row; gap: 30px;">
            <div>
                <a asp-area="" asp-controller="OurServices" asp-action="Index" style="color: black;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="27" height="27" fill="currentColor" class="bi bi-car-front-fill" viewBox="0 0 16 16" style="cursor: pointer;">
                        <path d="M2.52 3.515A2.5 2.5 0 0 1 4.82 2h6.362c1 0 1.904.596 2.298 1.515l.792 1.848c.075.175.21.319.38.404.5.25.855.715.965 1.262l.335 1.679q.05.242.049.49v.413c0 .814-.39 1.543-1 1.997V13.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-1.338c-1.292.048-2.745.088-4 .088s-2.708-.04-4-.088V13.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-1.892c-.61-.454-1-1.183-1-1.997v-.413a2.5 2.5 0 0 1 .049-.49l.335-1.68c.11-.546.465-1.012.964-1.261a.8.8 0 0 0 .381-.404l.792-1.848ZM3 10a1 1 0 1 0 0-2 1 1 0 0 0 0 2m10 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2M6 8a1 1 0 0 0 0 2h4a1 1 0 1 0 0-2zM2.906 5.189a.51.51 0 0 0 .497.731c.91-.073 3.35-.17 4.597-.17s3.688.097 4.597.17a.51.51 0 0 0 .497-.731l-.956-1.913A.5.5 0 0 0 11.691 3H4.309a.5.5 0 0 0-.447.276L2.906 5.19Z" />
                    </svg>
                </a>
            </div>
            @if (SignInManager.IsSignedIn(User))
            {
                <li style="text-decoration: none; list-style-type: none;">
                    <a style="color: #000;" id="manage" class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">
                        <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0" />
                            <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1" />
                        </svg>
                    </a>
                </li>
                <li style="text-decoration: none; list-style-type: none;">
                    @if (ViewBag.Pendente == null)
                    {
                        <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                            <button style="border:none; background-color: transparent;" id="logout" type="submit">
                                <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0z" />
                                    <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z" />
                                </svg>
                            </button>
                        </form>
                    }
                    else
                    {
                        <button style="text-decoration=none; list-style-type: none; border: none; background: none;" id="pendente">
                            <a style="color: #000;" asp-action="Pendente" asp-controller="CarroEscolhido" asp-area="">
                                <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-exclamation-triangle-fill" viewBox="0 0 16 16">
                                    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5m.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2" />
                                </svg>
                            </a>
                        </button>

                    }
                </li>
            }
            else
            {
                <div>
                    <a asp-area="Identity" asp-page="/Account/Login" style="color: black;">
                        <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16" style="cursor: pointer;">
                            <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6" />
                        </svg>
                    </a>
                </div>
            }
        </div>
    </nav>

    <a><img src="https://res.cloudinary.com/dtvypcack/image/upload/v1701711075/logo_recorte_dxihjz.png" class="logo"></a>
    <nav class="navbar-desktop">
        <ul>
            <li><a asp-action="Index" asp-area="" asp-controller="Home" class="button-home">Home</a></li>
            <li><a asp-area="" asp-controller="OurServices" asp-action="Index">Categorias</a></li>
            @if (User.IsInRole("Admin"))
            {
                <li class="nav-item dropdown">
                    <a href="#">Admin</a>
                    <ul class="dropdown-menu">
                        <li><a class="add" asp-area="" asp-controller="Carros" asp-action="Adicionar">Add Carro</a></li>
                        <li><a class="listando" asp-area="" asp-controller="Carros" asp-action="Listar">Listar Carros</a></li>
                        <li>
                            <a class="add" id="register" asp-area="Identity" asp-page="/Account/Register">Registrar</a>
                        </li>
                        <li><a class="dash, listando" asp-area="" asp-action="Index" asp-controller="Dashboard">Dash</a></li>
                        <li><a class="add" asp-area="" asp-action="AdicionarMP" asp-controller="ChatBot">Add ChatBot</a></li>
                        <li><a class="listando" asp-area="" asp-action="Index" asp-controller="ChatBot">Listar ChatBot</a></li>
                    </ul>
                </li>
            }
            <partial name="_LoginPartial" />
    </nav>
</header>
    <article class="article-description">

        <h1>Aventure-se com a<span class="destaque-title"> LeanIt</span></h1>

        <img src="https://res.cloudinary.com/dubnbered/image/upload/v1702226094/elemento_titulos_ulz1x5_j0fyh8.png" class="line-style-orange" width="145rem" height="25rem">

        <p class="paragraph-description">Aventure-se com confiança e estilo, deixe o Leanit guiá-lo em direção à sua próxima grande aventura.</p>

    </article>
<div class="gradient"></div>
<main>
    <div class="cards-pontos-turisticos">
        <article class="ponto-turistico-1">
            <div class="turismo-texto">
                <h2>Prefeitura de Blumenau:</h2>
                <p>A a imponente Prefeitura Municipal se destaca como um ícone arquitetônico, exibindo a influência da colonização alemã na região. Com sua marcante fachada em estilo enxaimel, o prédio não apenas abriga o centro administrativo, mas também encapsula a rica história e cultura da cidade, atraindo visitantes em busca de beleza e significado histórico.</p>
            </div>

            <div class="img-1"></div>

        </article>

        <article class="ponto-turistico-2">

            <div class="img-2"></div>

            <div class="turismo-texto">
                <h2>Igreja Matriz:</h2>
                <p>A majestosa Igreja Matriz de Blumenau, dedicada a São Paulo Apóstolo, é um ícone de arquitetura sacra que mescla influências germânicas. Com sua imponência e vitrais deslumbrantes, a igreja é um ponto turístico que transcende a devoção religiosa, oferecendo aos visitantes uma experiência única de beleza histórica e cultural.</p>
            </div>

        </article>

        <article class="ponto-turistico-3">
            <div class="turismo-texto">
                <h2>Vila Germânica:</h2>
                <p>A Vila Germânica de Blumenau encanta os visitantes com sua atmosfera encantadora e arquitetura que evoca a tradição alemã. Este ponto turístico vibrante é conhecido por sediar eventos culturais, festivais e proporcionar uma experiência única, onde a gastronomia, a música e a cultura germânica se entrelaçam de maneira cativante.</p>
            </div>

            <div class="img-3"></div>

        </article>

        <article class="ponto-turistico-4">

            <div class="img-4"></div>

            <div class="turismo-texto">
                <h2>Castelinho da XV:</h2>
                <p>O Castelinho da XV, um notável ponto turístico de Blumenau, é uma construção histórica que remete à herança arquitetônica da colonização alemã na região. Com sua fachada encantadora, o Castelinho preserva a rica história local, proporcionando aos visitantes uma imersão na cultura e no charme característicos da cidade.</p>
            </div>

        </article>
    </div>
</main>

<footer>

    <div class="footer-main">
        <div class="footer-about">
            <p class="footer-title">Sobre a LeanIt</p>
            <p class="footer-paragraph-about">Nós levamos a outro nível a locomoção por meio de nossa tecnologia</p>
            <div class="icons-about"><a href="#"><i class="fa-brands fa-youtube"></a></i> <a href="https://pt-br.facebook.com/"><i class="fa-brands fa-facebook"></a></i> <a href="https://www.instagram.com/_leanit?igsh=M2R2amd0ejFyeWky"><i class="fa-brands fa-instagram"></i></a> <a href="https://twitter.com/"><i class="fa-brands fa-square-x-twitter"></i></a></div>
        </div>

        <div class="footer-extra">
            <p class="footer-title">Nossa Página</p>
            <p>@Html.ActionLink("Nosso blog", "Index", "Blog")</p>
            <p><a href="https://www.entra21.com.br/" target="_blank">Entra21</a></p>
            <p>@Html.ActionLink("Guia Turístico", "Index", "Turismo")</p>
            <p>@Html.ActionLink("Termos de Uso", "Index", "Termos")</p>
        </div>

        <div class="footer-contact">
            <p class="footer-title">Contate-nos</p>
            <p class="paragraph-contact paragraph-contact-top"><i class="fa-solid fa-phone phone-icon"></i>+55 (47) 9999-9999</p>
            <p class="paragraph-contact"><i class="fa-solid fa-envelope email-icon"></i><a href="#">contact@leanit.com</a></p>
        </div>
    </div>

    <p class="footer-copyright">Copyright © 2023 All rights deserved</p>

</footer>

@section Styles {
    <link rel="stylesheet" href="~/css/turismo.css" />
}
@section Scripts {
    <script src="~/js/contagemMinutos.js"></script>
}